module.exports = {

    SUCCESS: 200,
    INTERNAL_ERROR: 500,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    DUPLICATE: 409,
    NOT_FOUND: 404,
    HTTP_UNPROCESSABLE_ENTITY: 422,

    // User message
    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
    USER_CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    USER_NOT_CREATED: 'USER_NOT_CREATED',
    PASSWORD_NOT_FOUND: 'PASSWORD_NOT_FOUND',
    INVALID_CURRENT_PASSWORD_NOT_VALID: 'INVALID_CURRENT_PASSWORD_NOT_VALID',
    INVALID_EMAIL: 'INVALID_EMAIL',
    PLEASE_PROVIDE_ID: 'PLEASE_PROVIDE_ID',
    INTERNAL_SERVER_ERROR: 'Internal server error.',
    ID_DOES_NOT_EXIST: 'ID_DOES_NOT_EXIST',
    PASSWORD_RESET_SUCCESS: 'Password has been reset.',

    // Role
    ROLE_ALREADY_EXIST: 'ROLE_ALREADY_EXIST',
    ROLE_CREATE_SUCCESS: 'ROLE_CREATE_SUCCESS',
    ROLE_UPDATE_SUCCESS: 'ROLE_UPDATE_SUCCESS',
    ROLE_DELETE_SUCCESS: 'ROLE_DELETE_SUCCESS',
    ROLE_IN_USE: 'ROLE_IN_USE',

    // Location
    LOCATION_ALREADY_EXIST: 'LOCATION_ALREADY_EXIST',
    LOCATION_CREATE_SUCCESS: 'LOCATION_CREATE_SUCCESS',
    LOCATION_DELETE_SUCCESS: 'LOCATION_DELETE_SUCCESS',
    LOCATION_UPDATE_SUCCESS: 'LOCATION_UPDATE_SUCCESS',
    LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
    LOCATION_IN_USE: 'LOCATION_IN_USE',

    // ORGANISATION
    ORGANISATION_ALREADY_EXIST: 'ORGANISATION_ALREADY_EXIST',
    ORGANISATION_CREATE_SUCCESS: 'ORGANISATION_CREATE_SUCCESS',
    ORGANISATION_UPDATE_SUCCESS: 'ORGANISATION_UPDATE_SUCCESS',
    ORGANISATION_DELETE_SUCCESS: 'ORGANISATION_DELETE_SUCCESS',

    // RESOURCE TYPE
    RESOURCE_TYPE_ALREADY_EXIST: 'RESOURCE_TYPE_ALREADY_EXIST',
    RESOURCE_TYPE_CREATE_SUCCESS: 'RESOURCE_TYPE_CREATE_SUCCESS',
    RESOURCE_TYPE_DELETE_SUCCESS: 'RESOURCE_TYPE_DELETE_SUCCESS',
    RESOURCE_TYPE_UPDATE_SUCCESS: 'RESOURCE_TYPE_UPDATE_SUCCESS',
    RESOURCE_TYPE_IN_USE: 'RESOURCE_TYPE_IN_USE',
    RESOURCE_TYPE_NOT_FOUND: 'RESOURCE_TYPE_NOT_FOUND',

    // RESOURCE_CATEGORY
    RESOURCE_CATEGORY_ALREADY_EXIST: 'RESOURCE_CATEGORY_ALREADY_EXIST',
    RESOURCE_CATEGORY_CREATE_SUCCESS: 'RESOURCE_CATEGORY_CREATE_SUCCESS',
    RESOURCE_CATEGORY_DELETE_SUCCESS: 'RESOURCE_CATEGORY_DELETE_SUCCESS',
    RESOURCE_CATEGORY_UPDATE_SUCCESS: 'RESOURCE_CATEGORY_UPDATE_SUCCESS',
    RESOURCE_CATEGORY_IN_USE: 'RESOURCE_CATEGORY_IN_USE',
    RESOURCE_CATEGORY_NOT_FOUND: 'RESOURCE_CATEGORY_NOT_FOUND',

    // RESOURCE_MANUFACTURER
    RESOURCE_MANUFACTURER_ALREADY_EXIST: 'RESOURCE_MANUFACTURER_ALREADY_EXIST',
    RESOURCE_MANUFACTURER_CREATE_SUCCESS: 'RESOURCE_MANUFACTURER_CREATE_SUCCESS',
    RESOURCE_MANUFACTURER_DELETE_SUCCESS: 'RESOURCE_MANUFACTURER_DELETE_SUCCESS',
    RESOURCE_MANUFACTURER_UPDATE_SUCCESS: 'RESOURCE_MANUFACTURER_UPDATE_SUCCESS',
    RESOURCE_MANUFACTURER_IN_USE: 'RESOURCE_MANUFACTURER_IN_USE',
    RESOURCE_MANUFACTURER_NOT_FOUND: 'RESOURCE_MANUFACTURER_NOT_FOUND',

    // token
    UNAUTHORIZED_ACCESS: 'Unauthorized access.',
    PROVIDE_LOCATION: 'Please provide location.',
    MISSING_SAP_IDENTIFIER: 'MISSING_SAP_IDENTIFIER',

    // Resource
    RESOURCE_ALREADY_EXIST: 'RESOURCE_ALREADY_EXIST',
    RESOURCE_CREATE_SUCCESS: 'RESOURCE_CREATE_SUCCESS',
    RESOURCE_CREATE_FAILURE: 'RESOURCE_CREATE_FAILURE',
    RESOURCE_UPDATE_SUCCESS: 'RESOURCE_UPDATE_SUCCESS',
    RESOURCE_DELETE_SUCCESS: 'RESOURCE_DELETE_SUCCESS',
    RESOURCE_UPDATE_FAILURE: 'RESOURCE_UPDATE_FAILURE',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    RESOURCES_ADDED: 'RESOURCES_ADDED',
    RESOURCE_ALREADY_ADDED: 'RESOURCE_ALREADY_ADDED',
    RESOURCE_IN_USE: 'RESOURCE_IN_USE',
    RESOURCES_CREATE_SUCCESS: 'RESOURCES_CREATE_SUCCESS',
    ALL_RESOURCES_DUPLICATE: 'ALL_RESOURCES_DUPLICATE',
    SAP_IDENTIFIER_DOES_NOT_EXIST: 'SAP_IDENTIFIER_DOES_NOT_EXIST',

    // process
    PROCESS_ALREADY_EXIST: 'PROCESS_ALREADY_EXIST',
    PROCESS_CREATE_SUCCESS: 'PROCESS_CREATE_SUCCESS',
    PROCESS_DELETE_SUCCESS: 'PROCESS_DELETE_SUCCESS',
    PROCESS_UPDATE_SUCCESS: 'PROCESS_UPDATE_SUCCESS',
    PROVIDE_DATA_TO_UPDATE: 'Nothing to updated',
    PROCESS_NOT_FOUND: 'PROCESS_NOT_FOUND',
    PROCESS_IN_USE: 'PROCESS_IN_USE',
    PROCESS_DOES_NOT_EXIST: 'PROCESS_DOES_NOT_EXIST',

    // group
    GROUP_ALREADY_EXIST: 'GROUP_ALREADY_EXIST',
    GROUP_CREATE_SUCCESS: 'GROUP_CREATE_SUCCESS',
    GROUP_DELETE_SUCCESS: 'GROUP_DELETE_SUCCESS',
    GROUP_UPDATE_SUCCESS: 'GROUP_UPDATE_SUCCESS',
    GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
    GROUP_IN_USE: 'GROUP_IN_USE',

    // organisation
    ORGANISATION_DELETED: 'Organisation has been deleted',
    ORGANISATION_UPDATED: 'Organisation has been updated',

    // attributeType
    ATTRIBUTE_TYPE_ALREADY_EXIST: 'ATTRIBUTE_TYPE_ALREADY_EXIST',
    ATTRIBUTE_TYPE_CREATE_SUCCESS: 'ATTRIBUTE_TYPE_CREATE_SUCCESS',
    ATTRIBUTE_TYPE_DELETE_SUCCESS: 'ATTRIBUTE_TYPE_DELETE_SUCCESS',
    ATTRIBUTE_TYPE_UPDATE_SUCCESS: 'ATTRIBUTE_TYPE_UPDATE_SUCCESS',
    ATTRIBUTE_TYPE_NOT_FOUND: 'ATTRIBUTE_TYPE_NOT_FOUND',

    // attributeGroup
    ATTRIBUTE_GROUP_ALREADY_EXIST: 'ATTRIBUTE_GROUP_ALREADY_EXIST',
    ATTRIBUTE_GROUP_CREATE_SUCCESS: 'ATTRIBUTE_GROUP_CREATE_SUCCESS',
    ATTRIBUTE_GROUP_DELETE_SUCCESS: 'ATTRIBUTE_GROUP_DELETE_SUCCESS',
    ATTRIBUTE_GROUP_UPDATE_SUCCESS: 'ATTRIBUTE_GROUP_UPDATE_SUCCESS',
    ATTRIBUTE_GROUP_IN_USE: 'ATTRIBUTE_GROUP_IN_USE',
    ATTRIBUTE_GROUP_NOT_FOUND: 'ATTRIBUTE_GROUP_NOT_FOUND',
    ATTRIBUTE_FIELD_MAPPING_UPDATE_SUCCESS: 'ATTRIBUTE_FIELD_MAPPING_UPDATE_SUCCESS',

    // attribute
    ATTRIBUTE_ALREADY_EXIST: 'ATTRIBUTE_ALREADY_EXIST',
    ATTRIBUTE_CREATE_SUCCESS: 'ATTRIBUTE_CREATE_SUCCESS',
    ATTRIBUTE_DELETE_SUCCESS: 'ATTRIBUTE_DELETE_SUCCESS',
    ATTRIBUTE_UPDATE_SUCCESS: 'ATTRIBUTE_UPDATE_SUCCESS',
    ATTRIBUTE_NOT_FOUND: 'ATTRIBUTE_NOT_FOUND',
    ATTRIBUTE_ID_NOT_EXIST: 'ATTRIBUTE_ID_NOT_EXIST',
    ORDER_UPDATED: 'ORDER_UPDATED',

    // Process Step
    PROCESS_STEP_ALREADY_EXIST: 'PROCESS_STEP_ALREADY_EXIST',
    PROCESS_STEP_CREATE_SUCCESS: 'PROCESS_STEP_CREATE_SUCCESS',
    PROCESS_STEP_DELETE_SUCCESS: 'PROCESS_STEP_DELETE_SUCCESS',
    PROCESS_STEP_UPDATE_SUCCESS: 'PROCESS_STEP_UPDATE_SUCCESS',
    PROCESS_STEP_NOT_FOUND: 'PROCESS_STEP_NOT_FOUND',

    // order
    ORDER_ALREADY_EXIST: 'ORDER_ALREADY_EXIST',
    ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
    ORDER_DELETE_SUCCESS: 'ORDER_DELETE_SUCCESS',
    ORDER_UPDATE_SUCCESS: 'ORDER_UPDATE_SUCCESS',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_NOT_CREATED: 'ORDER_NOT_CREATED',
    ORDER_CREATE_FAILURE: 'ORDER_CREATE_FAILURE',

};
